version: "3.8"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: dietrydb

  app:
    image: dietry-app
    ports:
      - 5000:5000
